export enum EventStatusEnum {
  TimeToBeDefined = 'Time To Be Defined',
  NotStarted = 'Not Started',
  FirstHalfKickOff = 'First Half, Kick Off',
  Halftime = 'Halftime',
  SecondHalf2ndHalfStarted = 'Second Half, 2nd Half Started',
  ExtraTime = 'Extra Time',
  PenaltyInProgress = 'Penalty In Progress',
  MatchFinished = 'Match Finished',
  MatchFinishedAfterExtraTime = 'Match Finished After Extra Time',
  MatchFinishedAfterPenalty = 'Match Finished After Penalty',
  BreakTime = 'Break Time (in Extra Time)',
  MatchSuspended = 'Match Suspended',
  MatchInterrupted = 'Match Interrupted',
  MatchPostponed = 'Match Postponed',
  MatchCancelled = 'Match Cancelled',
  MatchAbandoned = 'Match Abandoned',
  TechnicalLoss = 'Technical Loss',
  WalkOver = 'WalkOver',
}
